### ISSUE TITLE
TDW not compatible with Jupyter Notebook on VSCode

### ISSUE THREAD

**Issue by YudiXie** [threedworld-mit/tdw#654]
I am using the jupyter notebook on VSCode to test some TDW commands.

It seems that the current version of TDW is not compatible with the notebook, likely because of the use of `ArgumentParser` when initializing the build.

Steps to reproduce the error:
In VSCode, create a jupyter notebook, select the kernel to be the conda environment where TDW is installed. and run the following
```
from tdw.controller import Controller

c = Controller()
```
I got the following errors:
```
usage: ipykernel_launcher.py [-h] [--flip_images] [--force_glcore42]
ipykernel_launcher.py: error: ambiguous option: --f=/Users/yudixie/Library/Jupyter/runtime/kernel-v2-11593GW1toGm63O1Y.json could match --flip_images, --force_glcore42

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

/opt/anaconda3/envs/tdw/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

If I use %tb in the notebook to see the full traceback, this is what I got.
```
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
[/Users/yudixie/PycharmProjects/tdw_image_dataset/analysis_scripts/1030materials.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/yudixie/PycharmProjects/tdw_image_dataset/analysis_scripts/1030materials.ipynb) Cell 3 line 1
----> [1](vscode-notebook-cell:/Users/yudixie/PycharmProjects/tdw_image_dataset/analysis_scripts/1030materials.ipynb#X14sZmlsZQ%3D%3D?line=0) c = Controller()
      [2](vscode-notebook-cell:/Users/yudixie/PycharmProjects/tdw_image_dataset/analysis_scripts/1030materials.ipynb#X14sZmlsZQ%3D%3D?line=1) print("Hello world!")
      [3](vscode-notebook-cell:/Users/yudixie/PycharmProjects/tdw_image_dataset/analysis_scripts/1030materials.ipynb#X14sZmlsZQ%3D%3D?line=2) c.communicate({"$type": "terminate"})

File [/opt/anaconda3/envs/tdw/lib/python3.9/site-packages/tdw/controller.py:70](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/site-packages/tdw/controller.py:70), in Controller.__init__(self, port, check_version, launch_build)
     68 # Launch the build.
     69 if launch_build and can_launch_build:
---> 70     Controller.launch_build(port=port)
     71 context = zmq.Context()
     72 # noinspection PyUnresolvedReferences

File [/opt/anaconda3/envs/tdw/lib/python3.9/site-packages/tdw/controller.py:567](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/site-packages/tdw/controller.py:567), in Controller.launch_build(port)
    565 parser.add_argument("--flip_images", action="store_true")
    566 parser.add_argument("--force_glcore42", action="store_true")
--> 567 args, unknown = parser.parse_known_args()
    568 build_call = [str(BUILD_PATH.resolve()), "-port " + str(port)]
    569 if args.flip_images:

File [/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:1858](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:1858), in ArgumentParser.parse_known_args(self, args, namespace)
   1856 if self.exit_on_error:
   1857     try:
-> 1858         namespace, args = self._parse_known_args(args, namespace)
   1859     except ArgumentError:
   1860         err = _sys.exc_info()[1]

File [/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:1902](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:1902), in ArgumentParser._parse_known_args(self, arg_strings, namespace)
   1897         arg_string_pattern_parts.append('A')
   1899 # otherwise, add the arg to the arg strings
   1900 # and note the index if it was an option
   1901 else:
-> 1902     option_tuple = self._parse_optional(arg_string)
   1903     if option_tuple is None:
   1904         pattern = 'A'

File [/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2218](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2218), in ArgumentParser._parse_optional(self, arg_string)
   2216     args = {'option': arg_string, 'matches': options}
   2217     msg = _('ambiguous option: %(option)s could match %(matches)s')
-> 2218     self.error(msg % args)
   2220 # if exactly one action matched, this segmentation is good,
   2221 # so return the parsed action
   2222 elif len(option_tuples) == 1:

File [/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2582](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2582), in ArgumentParser.error(self, message)
   2580 self.print_usage(_sys.stderr)
   2581 args = {'prog': self.prog, 'message': message}
-> 2582 self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

File [/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2569](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/tdw/lib/python3.9/argparse.py:2569), in ArgumentParser.exit(self, status, message)
   2567 if message:
   2568     self._print_message(message, _sys.stderr)
-> 2569 _sys.exit(status)

SystemExit: 2
```

**Comment by YudiXie** [comment]
I tested that this issue doesn't happen on version `1.12.8`, but later versions from `1.12.10` or later appear to have this issue.

**Comment by YudiXie** [comment]
This issue seems to result from a known issue in ArgumentParser,
https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.parse_known_args

I guess the Jupyter Notebook will provide the argument. `--f` for its own use, which may be in conflict with the `--flip_images` `--force_glcore42` arguments in the controller setup in TDW.

**Comment by alters-mit** [comment]
This issue might've been resolved in the most recent TDW update. Can you check?

**Comment by YudiXie** [comment]
I just checked that I have `tdw-1.12.15.0`, and this still happens.
